async function createDefaultData(db) {
  const characteristics = [
  { name: 'Тип футболки' }, 
  { name: 'Цвет футболки' }, 
  { name: 'Размер футболки' }, 
  { name: 'Печать на груди' }, 
  { name: 'Печать на спине' }, 
  { name: 'Цвет кружки' }, 
  { name: 'Материал подушки' }, 
  { name: 'Сторона печати' }, 
  { name: 'Размер магнита' }, 
  { name: 'Форма пазла' },  
  { name: 'Размер фото' }, 
  { name: 'Тип бумаги' }, 
  { name: 'Ламинация' }, 
  { name: 'Ламинация' }, 
  { name: 'Срочность' }, 
  { name: 'Формат листовки' }, 
  { name: 'Тираж' }, 
  { name: 'Формат флаеров' }, 
  { name: 'Формат плакатов' }, 
  { name: 'Формат документов' }, 
  { name: 'Тип бумаги (мм)' }, 
  { name: 'Цвет печати' },  
  ]
  for (const characteristic of characteristics) {
    await db.characteristics.create(characteristic)
  }
  const characteristicsValues = [
    { characteristicId: 11, strValue: 'Полароид' },
    { characteristicId: 11, strValue: 'А6 10х15' },
    { characteristicId: 11, strValue: 'А5 15х20' },
    { characteristicId: 11, strValue: 'А4 20х30' },
    { characteristicId: 11, strValue: 'А3 30х40' },
    { characteristicId: 12, strValue: 'Глянцевая' },
    { characteristicId: 12, strValue: 'Матовая' },
    { characteristicId: 20, strValue: 'Не требуется' },
    { characteristicId: 20, strValue: 'Пленка (80 мкм)' },
    { characteristicId: 1, strValue: 'Мужская' },
    { characteristicId: 1, strValue: 'Женская' },
    { characteristicId: 2, strValue: 'Белый' },
    { characteristicId: 2, strValue: 'Розовый' },
    { characteristicId: 2, strValue: 'Серый' },
    { characteristicId: 2, strValue: 'Черный' },
    { characteristicId: 3, strValue: 'S' },
    { characteristicId: 3, strValue: 'M' },
    { characteristicId: 3, strValue: 'L' },
    { characteristicId: 3, strValue: 'XL' },
    { characteristicId: 4, strValue: 'Нет' },
    { characteristicId: 4, strValue: 'А4' },
    { characteristicId: 5, strValue: 'Нет' },
    { characteristicId: 5, strValue: 'А4' },
    { characteristicId: 6, strValue: 'Белая' },
    { characteristicId: 6, strValue: 'Цветная' },
    { characteristicId: 6, strValue: 'Хамелеон' },
    { characteristicId: 6, strValue: 'Пивная' },
    { characteristicId: 6, strValue: 'Парные кружки' },
    { characteristicId: 7, strValue: 'Атлас' },
    { characteristicId: 7, strValue: 'С пайетками' },
    { characteristicId: 7, strValue: 'Супермягкая' },
    { characteristicId: 8, strValue: 'Односторонняя' },
    { characteristicId: 8, strValue: 'Двухсторонняя' },
    { characteristicId: 9, strValue: '5x5' },
    { characteristicId: 9, strValue: '7x7' },
    { characteristicId: 9, strValue: '9х9' },
    { characteristicId: 9, strValue: '15х15' },
    { characteristicId: 9, strValue: '7.5х5' },
    { characteristicId: 10, strValue: 'Прямоугольный' },
    { characteristicId: 10, strValue: 'Сердце' },
    { characteristicId: 8, strValue: 'Односторонняя' },
    { characteristicId: 8, strValue: 'Двухсторонняя' },
    { characteristicId: 14 , strValue: 'Без ламинации' },
    { characteristicId: 14 , strValue: 'Матовая' },
    { characteristicId: 14 , strValue: 'Гляцевая' },
    { characteristicId: 15 , strValue: '3 рабочих дня' },
    { characteristicId: 15 , strValue: ' 24 часа' },
    { characteristicId: 16, strValue: 'А6' },
    { characteristicId: 16, strValue: 'А5' },
    { characteristicId: 16, strValue: 'А4' },
    { characteristicId: 8, strValue: 'Односторонняя' },
    { characteristicId: 8, strValue: 'Двухсторонняя' },
    { characteristicId: 17, strValue: '20 шт' },
    { characteristicId: 17, strValue: '50 шт' },
    { characteristicId: 17, strValue: '100 шт' },
    { characteristicId: 17, strValue: '200 шт' },
    { characteristicId: 17, strValue: '500 шт' },
    { characteristicId: 17, strValue: ' 1000 шт' },
    { characteristicId: 18, strValue: 'Евро' },
    { characteristicId: 18, strValue: 'А6' },
    { characteristicId: 8, strValue: 'Односторонняя' },
    { characteristicId: 8, strValue: 'Двухсторонняя' },
    { characteristicId: 17, strValue: '20 шт' },
    { characteristicId: 17, strValue: '50 шт' },
    { characteristicId: 17, strValue: '100 шт' },
    { characteristicId: 17, strValue: '200 шт' },
    { characteristicId: 17, strValue: '500 шт' },
    { characteristicId: 17, strValue: ' 1000 шт' },
    { characteristicId: 19, strValue: 'А3' },
    { characteristicId: 19, strValue: 'А2' },
    { characteristicId: 19, strValue: 'А1' },
    { characteristicId: 8, strValue: 'Односторонняя' },
    { characteristicId: 8, strValue: 'Двухсторонняя' },
    { characteristicId: 17, strValue: '20 шт' },
    { characteristicId: 17, strValue: '50 шт' },
    { characteristicId: 17, strValue: '100 шт' },
    { characteristicId: 17, strValue: '200 шт' },
    { characteristicId: 17, strValue: '500 шт' },
    { characteristicId: 17, strValue: ' 1000 шт' },
    { characteristicId: 20, strValue: 'А4' },
    { characteristicId: 20, strValue: 'А3' },
    { characteristicId: 21, strValue: '80 гр' },
    { characteristicId: 21, strValue: '150 гр' },
    { characteristicId: 21, strValue: '300 гр' },
    { characteristicId: 22, strValue: 'Цветная' },
    { characteristicId: 22, strValue: 'Черно-белая' },
    { characteristicId: 14 , strValue: 'Без ламинации' },
    { characteristicId: 14 , strValue: 'Матовая' },
    { characteristicId: 14 , strValue: 'Гляцевая' },
  ]
  for (const characteristicValue of characteristicsValues) {
    await db.characteristicsValues.create(characteristicValue)
  }
  const categories = [
    { name: 'Фотопечать' },
    { name: 'Печать документов' },
    { name: 'Произвольный заказ' },
    { name: 'Печать на сувенирах' },
    { name: 'Печать полиграфии' },
  ]
  for (const category of categories) {
    await db.categories.create(category)
  }
  const products = [
    { categoryId: 1, name: 'Футболки', categoryId: 4 },
    { categoryId: 1, name: 'Кружки', categoryId: 4 },
    { categoryId: 1, name: 'Подушки', categoryId: 4 },
    { categoryId: 1, name: 'Магниты', categoryId: 4 },
    { categoryId: 1, name: 'Пазлы', categoryId: 4 },
    { categoryId: 1, name: 'Визитки', categoryId: 5 },
    { categoryId: 1, name: 'Листовки', categoryId: 5 },
    { categoryId: 1, name: 'Флаеры', categoryId: 5 },
    { categoryId: 1, name: 'Плакаты', categoryId: 5 },
    { categoryId: 1, name: 'Произвольный заказ', categoryId: 3 },
    { categoryId: 1, name: 'Фотопечать', categoryId: 1 },
  ]
  for (const product of products) {
    await db.products.create(product)
  }
  const productsCharacteristics = [
    { productId: 1, characteristicId: 1 },
    { productId: 1, characteristicId: 2 },
    { productId: 1, characteristicId: 3 },
    { productId: 1, characteristicId: 4 },
    { productId: 1, characteristicId: 5 },
    { productId: 2, characteristicId: 6 },
    { productId: 3, characteristicId: 7 },
    { productId: 3, characteristicId: 8 },
    { productId: 4, characteristicId: 9 },
    { productId: 5, characteristicId: 10 },
    { productId: 6, characteristicId: 8 },
    { productId: 6, characteristicId: 14 },
    { productId: 6, characteristicId: 15 },
    { productId: 7, characteristicId: 16 },
    { productId: 7, characteristicId: 8 },
    { productId: 7, characteristicId: 17 },
    { productId: 8, characteristicId: 18 },
    { productId: 8, characteristicId: 8 },
    { productId: 8, characteristicId: 17 },
    { productId: 9, characteristicId: 19 },
    { productId: 9, characteristicId: 8 },
    { productId: 9, characteristicId: 17 },
    { productId: 10, characteristicId: 20 },
    { productId: 10, characteristicId: 21 },
    { productId: 10, characteristicId: 22 },
    { productId: 10, characteristicId: 14 },
    { productId: 11, characteristicId: 11 },
    { productId: 11, characteristicId: 12 },
    { productId: 11, characteristicId: 20 },
  ]
  for (const productCharacteristic of productsCharacteristics) {
    await db.productsCharacteristics.create(productCharacteristic)
  }
}


module.exports = createDefaultData